---

- name: update apt cache
  apt: "update_cache=yes cache_valid_time={{ ubuntu_cache_valid_time }}"

- name: install curl
  apt: pkg=curl state=present

- name: install python-pycurl
  apt: pkg=python-pycurl state=present

- name: install python-configparser
  apt: pkg=python-configparser state=present

- name: write inputrc
  copy: src=inputrc dest=/etc/inputrc owner=root group=root mode=0644
